### ISSUE TITLE
Add GitHub Actions

### ISSUE THREAD

**Issue by Cherry** [nodecraft/eslint-config-nodecraft#3]
There's not a lot of "test" here other than syntax. 

Please see https://github.com/nodecraft/b2-cloud-storage/pull/14 for details on what needs to be included. (Code coverage and other tests can be ignored). The `lint` script in `package.json` is what needs running.

- Workflow test.yml
- Readme badge

**Comment by danny95djb** [comment]
I'll have a go at this.

**Comment by Cherry** [comment]
Awesome @danny95djb 👍 Just submit a PR when you're ready and good luck on reaching your 4 PRs for Hacktoberfest!

**Comment by Cherry** [comment]
Closed by #4
